spring:
  profiles:
    active: @activeSpringProfile@
---
spring:
  profiles: local
  application:
    name: fsd-auth
server:
  servlet:
    context-path: /auth
  port: 9002
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    prefer-ip-address: true
    ipAddress: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
logging:
  config: classpath:logback-boot_dev.xml
 
---
spring:
  profiles: k8s
  application:
    name: fsd-auth
server:
  servlet:
    context-path: /auth
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://fsd-registry:8080/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
      #        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
logging:
  config: classpath:logback-boot_dev.xml

